#ifndef NETWORKING_RESEARCH_ANSI_COLORS_H
#define NETWORKING_RESEARCH_ANSI_COLORS_H

#define ANSI_COLOR_RESET "\x1b[0m"
#define ANSI_COLOR_TRACE "\x1b[90m"
#define ANSI_COLOR_INFO "\x1b[32m"
#define ANSI_COLOR_WARN "\x1b[33m"
#define ANSI_COLOR_ERR "\x1b[31m"
#define ANSI_COLOR_FATAL "\x1b[97;41m"

#endif
